import { ClerkProvider,SignIn } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { SignedIn } from '@clerk/nextjs'
import { SignedOut } from '@clerk/nextjs'
import NavBar from '@/components/NavBar'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>

        <SignedIn>
          {/* <NavBar/> */}
         {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
        
        </body>
    </html>
    </ClerkProvider>
  )
}
